apiVersion: v1
kind: Service
metadata:
  name: starbucks
  labels:
    app: starbucks
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: starbucks
  type: LoadBalancer